<Project>
  <PropertyGroup>
    <!--App版本-->
    <AppVersion>3.3</AppVersion>

    <!--Avalonia库版本-->
    <AvaloniaVersion>11.3.11</AvaloniaVersion>
    <!--FzLib库版本-->
    <FzLibVersion>3.3.2</FzLibVersion>

    <!--使用本地FzLib库。非作者使用时，应改为F-->
    <FzLocal>F</FzLocal>

    <!--在Windows上开发，可以设置输出到临时文件夹-->
    <OutputToTempDir>T</OutputToTempDir>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>CS0168,CS0169;MSB3539</NoWarn>
  </PropertyGroup>
</Project>