<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <WasmEnableLinker>false</WasmEnableLinker>
        <PublishTrimmed>false</PublishTrimmed>
        <IlcGenerateCompleteTypeMetadata>true</IlcGenerateCompleteTypeMetadata>
        <Version>$(AppVersion)</Version>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="FrpGUI.Avalonia"/>
    </ItemGroup>


    <ItemGroup Condition="'$(OutputToTempDir)' == 'T'">
        <AvaloniaXaml Remove="obj\**"/>
        <Compile Remove="obj\**"/>
        <Content Remove="obj\**"/>
        <EmbeddedResource Remove="obj\**"/>
        <None Remove="obj\**"/>
    </ItemGroup>

    <ItemGroup>
        <Content Remove="uiconfig.json"/>
        <Content Remove="web.config"/>
        <Content Remove="wwwroot\favicon.ico"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="uiconfig.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="wwwroot\favicon.ico">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="web.config">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FrpGUI.Avalonia\FrpGUI.Avalonia.csproj"/>
    </ItemGroup>
</Project>
