<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <BaseOutputPath>../Generation/bin</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OutputToTempDir)' == 'T'" >
    <OutputPath>$(Temp)\$(SolutionName)\$(Configuration)\$(AssemblyName)</OutputPath>
    <BaseIntermediateOutputPath>$(Temp)\$(SolutionName)\obj\$(Configuration)\$(AssemblyName)</BaseIntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(OutputToTempDir)' == 'T'" >
    <AvaloniaXaml Remove="obj\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
    <PackageReference Include="FzLib.Avalonia" Condition="'$(Configuration)' == 'Release' or '$(FzLocal)' == 'F'" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" />
    <PackageReference Include="System.Reactive" />
    <!--<PackageReference Include="WebView.Avalonia" />-->
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug' and '$(FzLocal)' == 'T'">
    <Reference Include="FzLib">
      <HintPath>..\..\FzLib\Publish\libs\FzLib.dll</HintPath>
    </Reference>
    <Reference Include="FzLib.Avalonia">
      <HintPath>..\..\FzLib\Publish\libs\FzLib.Avalonia.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrpGUI.Core\FrpGUI.Core.csproj" />
    <ProjectReference Include="..\FrpGUI.Service\FrpGUI.Service.csproj" />
  </ItemGroup>


  <ItemGroup>
    <AvaloniaResource Update="Assets\icon.ico">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Update="Views\RuleDialog.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\LogPanel.axaml.cs">
      <DependentUpon>LogPanel.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ControlBar.axaml.cs">
      <DependentUpon>ControlBar.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SettingsDialog.axaml.cs">
      <DependentUpon>SettingsDialog.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\RuleDialog.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>RuleDialog.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
