<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <BaseOutputPath>../Generation/bin</BaseOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <RootNamespace>FrpGUI</RootNamespace>
    </PropertyGroup>


    <ItemGroup>
        <AvaloniaXaml Remove="obj\**"/>
        <Compile Remove="obj\**"/>
        <EmbeddedResource Remove="obj\**"/>
        <None Remove="obj\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FrpGUI.Core\FrpGUI.Core.csproj"/>
    </ItemGroup>
</Project>
